version: '3.1'
services:
  ecc-provider:
    image: rdlabengpa/ids_execution_core_container:develop
    ports:
      - ${PROVIDER_PORT}:8449  #Port for exposing HTTP endpoints
      - 8889:8889  #Exposed port for receiving data from another connector (REST)
      - 8086:8086  #Exposed port for receiving data from another connector (WS)
    depends_on:
      - be-dataapp-provider
    networks:
      - provider
      - consumer
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      - DATA_APP_ENDPOINT=${PROVIDER_DATA_APP_ENDPOINT}               #Data APP enpoint for consuming received data
      - DATA_APP_HEALTH_ENDPOINT=${PROVIDER_DATA_APP_HEALTH_ENDPOINT}
      - MULTIPART_EDGE=${PROVIDER_MULTIPART_EDGE}                     #Data APP endpoint multipart/mixed content type
      - MULTIPART_ECC=${MULTIPART_ECC}
      - CONNECTOR_ID=${PROVIDER_ISSUER_CONNECTOR_URI}
      - IDSCP2=${IDSCP2}
      - WS_EDGE=${PROVIDER_WS_EDGE}
      - WS_ECC=${WS_ECC}
      - UC_DATAAPP_ENABLED=${UC_ENABLED}
      - UC_DATAAPP_URI=${PROVIDER_UC_DATAAPP_URI}
      - UC_DATAAPP_HEALTH_URI=${PROVIDER_UC_DATAAPP_HEALTH_URI}
      - PUBLIC_PORT=${PROVIDER_PORT}
      - BROKER_URL=${BROKER_URL}
      - CACHE_TOKEN=${CACHE_TOKEN}
      - FETCH_TOKEN_ON_STARTUP=${FETCH_TOKEN_ON_STARTUP}
      - KEYSTORE_NAME=${KEYSTORE_NAME}
      - KEY_PASSWORD=${KEY_PASSWORD}
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD}
      - ALIAS=${ALIAS}
      - DAPS_KEYSTORE_NAME=${PROVIDER_DAPS_KEYSTORE_NAME}
      - DAPS_KEYSTORE_PASSWORD=${PROVIDER_DAPS_KEYSTORE_PASSWORD}
      - DAPS_KEYSTORE_ALIAS=${PROVIDER_DAPS_KEYSTORE_ALIAS}
      - TRUSTORE_NAME=${TRUSTORE_NAME}
      - TRUSTORE_PASSWORD=${TRUSTORE_PASSWORD}
      - TZ=Europe/Rome
    volumes:
      - ./ecc_resources_provider:/config
      - ./ecc_cert:/cert
      - ecc_provider_log:/var/log/ecc
    extra_hosts:
      - "ecc-provider:127.0.0.1"

  uc-dataapp-provider:
    image: rdlabengpa/ids_uc_data_app_platoon:develop
    networks:
      - provider
    environment:
      - ECC_PORT=8449
      - ECC_SELF_DESCRIPTION_URL=${PROVIDER_ECC_SELF_DESCRIPTION_URL}
      - KEYSTORE_NAME=${KEYSTORE_NAME}
      - KEY_PASSWORD=${KEY_PASSWORD}
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD}
      - ALIAS=${ALIAS}
      - TZ=Europe/Rome
    expose:
      - "8180"
    volumes:
      - ./uc-dataapp_resources_provider:/config
      - uc_provider_data:/data
      - ./ecc_cert:/cert

  be-dataapp-provider:
    image: rdlabengpa/ids_be_data_app:develop
    networks:
      - provider
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      - DATA_APP_MULTIPART=${PROVIDER_MULTIPART_EDGE}
      - KEYSTORE_NAME=${KEYSTORE_NAME}
      - KEY_PASSWORD=${KEY_PASSWORD}
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD}
      - ALIAS=${ALIAS}
      - ECC_HOSTNAME=ecc-provider
      - ECC_PORT=8889
      - TZ=Europe/Rome
      - ISSUER_CONNECTOR_URI=${PROVIDER_ISSUER_CONNECTOR_URI}
      - EXTRACT_PAYLOAD_FROM_RESPONSE=${EXTRACT_PAYLOAD_FROM_RESPONSE}
      - CONTRACT_NEGOTIATION_DEMO=${CONTRACT_NEGOTIATION_DEMO}
    ports:
      - "8183:8183"
    expose:
      - "9000"
    volumes:
      - ./be-dataapp_resources:/config
      - ./be-dataapp_data_receiver:/home/nobody/data
      - ./ecc_cert:/cert

  ecc-consumer:
    image: rdlabengpa/ids_execution_core_container:develop
    ports:
      - ${CONSUMER_PORT}:8449  #Port for exposing HTTP endpoints
      - 8890:8889  #Exposed port for receiving data from another connector (REST)
      - 8087:8086  #Exposed port for receiving data from another connector (WS)
    depends_on:
      - be-dataapp-consumer
    networks:
      - provider
      - consumer
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      - DATA_APP_ENDPOINT=${CONSUMER_DATA_APP_ENDPOINT}               #Data APP enpoint for consuming received data
      - DATA_APP_HEALTH_ENDPOINT=${CONSUMER_DATA_APP_HEALTH_ENDPOINT}
      - MULTIPART_EDGE=${CONSUMER_MULTIPART_EDGE}                     #Data APP endpoint multipart/mixed content type
      - MULTIPART_ECC=${MULTIPART_ECC}
      - CONNECTOR_ID=${CONSUMER_ISSUER_CONNECTOR_URI}
      - IDSCP2=${IDSCP2}
      - WS_EDGE=${CONSUMER_WS_EDGE}
      - WS_ECC=${WS_ECC}
      - UC_DATAAPP_ENABLED=${UC_ENABLED}
      - UC_DATAAPP_URI=${CONSUMER_UC_DATAAPP_URI}
      - UC_DATAAPP_HEALTH_URI=${CONSUMER_UC_DATAAPP_HEALTH_URI}
      - PUBLIC_PORT=${CONSUMER_PORT}
      - BROKER_URL=${BROKER_URL}
      - CACHE_TOKEN=${CACHE_TOKEN}
      - FETCH_TOKEN_ON_STARTUP=${FETCH_TOKEN_ON_STARTUP}
      - KEYSTORE_NAME=${KEYSTORE_NAME}
      - KEY_PASSWORD=${KEY_PASSWORD}
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD}
      - ALIAS=${ALIAS}
      - DAPS_KEYSTORE_NAME=${CONSUMER_DAPS_KEYSTORE_NAME}
      - DAPS_KEYSTORE_PASSWORD=${CONSUMER_DAPS_KEYSTORE_PASSWORD}
      - DAPS_KEYSTORE_ALIAS=${CONSUMER_DAPS_KEYSTORE_ALIAS}
      - TRUSTORE_NAME=${TRUSTORE_NAME}
      - TRUSTORE_PASSWORD=${TRUSTORE_PASSWORD}
      - TZ=Europe/Rome
    volumes:
      - ./ecc_resources_consumer:/config
      - ./ecc_cert:/cert
      - ecc_consumer_log:/var/log/ecc
    extra_hosts:
      - "ecc-consumer:127.0.0.1"

  uc-dataapp-consumer:
    image: rdlabengpa/ids_uc_data_app_platoon:develop
    networks:
      - consumer
    environment:
      - ECC_PORT=8449
      - ECC_SELF_DESCRIPTION_URL=${CONSUMER_ECC_SELF_DESCRIPTION_URL}
      - KEYSTORE_NAME=${KEYSTORE_NAME}
      - KEY_PASSWORD=${KEY_PASSWORD}
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD}
      - ALIAS=${ALIAS}
      - TZ=Europe/Rome
    expose:
      - "8280"
    volumes:
      - ./uc-dataapp_resources_consumer:/config
      - uc_consumer_data:/data
      - ./ecc_cert:/cert

  be-dataapp-consumer:
    image: rdlabengpa/ids_be_data_app:develop
    networks:
      - consumer
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      - DATA_APP_MULTIPART=${CONSUMER_MULTIPART_EDGE}
      - KEYSTORE_NAME=${KEYSTORE_NAME}
      - KEY_PASSWORD=${KEY_PASSWORD}
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD}
      - ALIAS=${ALIAS}
      - ECC_HOSTNAME=ecc-consumer
      - ECC_PORT=8887
      - TZ=Europe/Rome
      - ISSUER_CONNECTOR_URI=${CONSUMER_ISSUER_CONNECTOR_URI}
      - EXTRACT_PAYLOAD_FROM_RESPONSE=${EXTRACT_PAYLOAD_FROM_RESPONSE}
      - CONTRACT_NEGOTIATION_DEMO=${CONTRACT_NEGOTIATION_DEMO}
    ports:
      - "8185:8183"
    expose:
      - "9000"
    volumes:
      - ./be-dataapp_resources:/config
      - be-dataapp_data_sender:/home/nobody/data
      - ./ecc_cert:/cert

networks:
  consumer: { }
  provider: { }

volumes:
  ecc_provider_log: { }
  ecc_consumer_log: { }
  uc_provider_data: { }
  uc_consumer_data: { }
  be-dataapp_data_sender: { }
