name: Master release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release version  (ie 5.5.0)'
        required: true
      developmentVersion:
        decription: 'Next development version, with SNAPSHOT'
        required: true
      tagVersion:
        description: 'Tag version'
        required: true
      
jobs:
  master_release:
    if: "!contains(github.event.head_commit.message, '[maven-release-plugin]')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Initialize mandatory git config
      run: |
        git config user.name "GitHub Actions"
        git config user.email noreply@github.com

    - name: ssh-agent
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}
        
    - name: Release with Maven
      env:
        GITHUB_USERNAME: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_PACKAGE_REPO_PASSWORD: ${{ secrets.GH_PACKAGE_REPO_PASSWORD }}
      run: |
        mvn -B -Dtag=${{ github.event.inputs.tagVersion }} release:prepare \
        -DreleaseVersion=${{ github.event.inputs.releaseVersion }} \
        -DdevelopmentVersion=${{ github.event.inputs.developmentVersion }} --file pom.xml \
        && mvn release:perform -B --file pom.xml
          
    - name: Create A Pull Request
      uses: thomaseizinger/create-pull-request@1.3.0
      with:
        github_token:  ${{ secrets.GITHUB_TOKEN }}
        head: master
        base: develop
        title: Released master into develop
        body: |
              Hi!
              This PR was created in response workflow running.
              I've updated the version name and code commit: ${{ steps.make-commit.outputs.commit }}.
